version: '3'
services:
  todolist-02-nginx:
    container_name: "todolist-02-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - todolist-02-app
    ports:
      - 80:80
    volumes:
      - ./:/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  todolist-02-app:
    container_name: "todolist-02-app"
    build:
      context: ./docker/php
    depends_on:
      - todolist-02-mysql
    volumes:
      - ./:/src
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  todolist-02-mysql:
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "todolist-02-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root  # rootユーザーのパスワードを設定
    ports:
      - 3306:3306
    networks:
      - app-network

  todolist-02-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "todolist-02-phpmyadmin"
    ports:
      - 8080:80
    environment:
      - PMA_HOST=todolist-02-mysql
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
